# See https://pre-commit.com for more information
# See https://pre-commit.com/hooks.html for more hooks
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      # All non-bat files should end with LF
      - id: mixed-line-ending
        args: ["--fix=lf"]
        exclude: |
          (?x)(
            \.bat$|
            ^NOT-EXISTING-LAST-ENTRY$
          )
      # Bat files should be CRLF ending
      - id: mixed-line-ending
        args: ["--fix=crlf"]
        files: \.bat$

  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@2.8.1
          - prettier-plugin-svelte@2.7.0
        exclude: |
          (?x)(
            /pnpm-lock.yaml$|
            ^NOT-EXISTING-LAST-ENTRY$
          )
