on:
  pull_request:
    types: [opened, synchronize, edited]
  push:
    branches:
      - "main"

name: Run validations for changes

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@c85c95e3d7251135ab7dc9ce3241c5835cc595a9 # v3.5.3

      - uses: actions/setup-node@5e21ff4d9bc1a8cf6de233a3057d20ec6b3fb69d # v3.8.1
        with:
          node-version: 18

      - uses: pnpm/action-setup@d882d12c64e032187b2edb46d3a0d003b7a43598 # v2.4.0
        with:
          version: 8

      - name: Install dependencies
        run: |
          pip install pre-commit
          cd builder && pnpm install && cd -

      # Run pre-commit --all-files
      - uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507 # v3.0.0

      # Commit all changed files back to the repository
      - uses: stefanzweifel/git-auto-commit-action@3ea6ae190baf489ba007f7c92608f33ce20ef04a # v4.16.0
        if: always()
